### ISSUE TITLE
Missing Appendix

### ISSUE THREAD

**Issue by guserav** [dhbw-stginf16a/nosql-book#11]
Currently there is no possibility to add large graphics or code examples at the end of the book.
This would be nice as a code example > 1 page seems odd in the book itself.

The requested is focused on but not limited to [this](https://github.com/dhbw-stginf16a/exploring-cassandra/blob/master/sparse_rows)

**Comment by lschuermann** [comment]
Thanks for creating the issue that we've definitely not talked about a few seconds ago.

Have you already looked into any solutions as of how this could be done in LaTeX? Basically, it would be a good idea to have some command in the user's chapter to put something into the appendix. The compiler could then build the appendix in order of occurrence.

I'll see whether I can find anything.

**Comment by guserav** [comment]
A brief search later there are two general approaches utilizing the package [appendix](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/appendix/appendix.pdf). The first would be to just use an appendix at the end starting with \appendix and section (ordered by us) in it that can be referenced normally using \ref.
Alternatively it is possible have a per chapter appendix utilizing the subappendices environment from the appendix package.
Both cases would be easy to implement but don't fulfill your (@lschuermann) requirements.

**Comment by JohnAZoidberg** [comment]
I'd choose the global appendix and do something like that in the main file:
```
\input{content/04_cassandra}
\input{content/05_graphdb}
\appendix
\input{appendix/04_cassandra}
\input{appendix/05_graphdb}
```

Yeah a solution like @lschuermann described would be the best but it doesn't seem like there are packages that do that.

**Comment by lschuermann** [comment]
I looked into various possible solutions but they all either do not fulfill our requirements or are way to complex.

@JohnAZoidberg's solution seems like it would be a good compromise between simplicity and having a clean structure. Would appreciate a PR.
